# Токен дискорд бота
token: "TOKEN"

# Добавление юзеров
# "NICK": DISCORD_ID
users:
  "1050TI_top": 817372400232169522

settings:
  # Время в секундах через которое игрока кикнет если он не подтвердит вход
  time: 30

  # Разрешенные команды во время подтверждения
  allowedCommands:
    - "/register"
    - "/reg"
    - "/login"
    - "/l"

messages:
  discord:
    # Эмодзи кнопки
    buttonEmoji: "✅"
    # Текст кнопки
    buttonText: "Подтвердить"

    # Сообщение отправляемое при входе на сервер
    join: "Подтвердите вход на сервер!"
    # Сообщение отправляемое при подтверждии входа
    allowJoin: "Вход подтвержден!"

    # Сообщение отправляемое если игрок уже подтвердил вход
    verifyNotRequired: "Подтверждение не требуется"

    # Сообщение отправляемое если игрок не найден на сервере
    playerNotFound: "Аккаунт не найден!"

  minecraft:
    # Сообщение отправляемое при входе на сервер
    join:
      - ""
      - " &fПодтвердите вход через &bDiscord&f!"
      - ""
    # Сообщение отправляемое при подтверждии входа
    allowJoin:
      - ""
      - " &fВход успешно выполнен!"
      - ""

    # Сообщение отправляемое при вводе команды без аргументов
    usage:
      - ""
      - "Команды:"
      - "/d2fa reload - перезагрузить конфиг"
      - ""
    # Сообщение отправляемое при перезагрузке конфига
    reload: "Конфиг перезагружен!"
    # Сообщение отправляемое при отсутствии прав на команду (tidiscord2fa.reload)
    noPermission: "&cНет прав!"

    # Сообщение при кике с сервера если игрок не успел подтвердить вход
    kick: "&cВы не успели подтвердить вход!"