name: tiDiscord2FA
version: '${version}'
main: ru.matveylegenda.tidiscord2fa.TiDiscord2FA
api-version: '1.16'
authors: [1050TI_top]
libraries:
  - net.elytrium:serializer:1.1.1
  - net.dv8tion:JDA:5.2.2
  - io.ktor:ktor-server-core:3.0.1
  - io.ktor:ktor-server-netty:3.0.1
  - io.ktor:ktor-client-cio:3.0.3
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3